Phase 6
Star-Academy/Summer1400-FE-Team9 pull request #7
Opened 2021-08-03 12:18 UTC by spneshaei

2021-08-06 15:53 UTC, MRSadeghi78 requested changes

2021-08-06 15:53 UTC, MRSadeghi78 commented on scripts/register.js
> +    let response = await fetch('http://130.185.120.192:5000/user/register', {
این مقادیر ثابت رو بهتره به شکل یک متغیر
const و global
تعریف بکنین که اگه خواستین تغییرشون بدین مجبور نباشین تو کل کد دنبالشون بگردین

2021-08-06 15:53 UTC, MRSadeghi78 commented on scripts/register.js
> +async function register() {
long method

2021-08-06 15:53 UTC, MRSadeghi78 commented on scripts/music.js
> +        twoXButton.style.color = "#4C956C";
"#4C956C": duplicate code

مقادیر ثابت توی متغیر
const
تعریف بشن

2021-08-06 15:53 UTC, MRSadeghi78 commented on scripts/login.js
> +            confirmButtonText: 'بازگشت',
این قسمت هم جاهای دیگه عینا تکرار شده. میتونید یه تابعش کنید و همه جا اون رو صدا بزنید

2021-08-07 05:43 UTC, rsangin requested changes

2021-08-07 05:43 UTC, rsangin commented on scripts/music-list.js
> +// let musics = [
کدهای کامنت رو حذف کنید تا حجم کد کمتر بشه

2021-08-07 05:43 UTC, rsangin commented on scripts/music-list.js
> +function renderPlayIcon() {
به جای این که تمام این متدها را داشته باشید میتونید یه تگ
template
داخل فایل های اچ تی ام ال داشته باشید و اون رو بخونید و مقادیر داخلش رو پر کنید. به این شکل کدها خوانایی بیشتری پیدا میکند.

2021-08-07 05:43 UTC, rsangin commented on styles/scss/music-list.scss
> +        padding: 1rem;
اینجا بهتره
width, height
بدید تا آیکن به شکل دایره بشه نه بیضی

2021-08-07 05:43 UTC, rsangin commented on styles/scss/music-list.scss
> +          background-color: rgba(0, 0, 0, 0.1);
برای هاور هم بهتره آیکن قرمز رنگ بشه و 
background
تغییری نکند.

2021-08-07 05:43 UTC, rsangin commented on styles/scss/music-list.scss
> +    box-shadow: rgba(0, 0, 0, 0.25) 0px 54px 55px, rgba(0, 0, 0, 0.12) 0px -12px 30px, rgba(0, 0, 0, 0.12) 0px 4px 6px, rgba(0, 0, 0, 0.17) 0px 12px 13px, rgba(0, 0, 0, 0.09) 0px -3px 5px;
بهتره روی کل این 
li
هم لینک بشه به صفحه آهنگ. همچنین برای این قسمت هم 
cursor: pointer;
قرار بگیره بهتره

2021-08-07 05:43 UTC, rsangin commented on styles/scss/music-list.scss
> +      text-align: right;
این قسمت بهتره یک خطی بشه تا کل تگ
li
از یه حدی بزرگتر نشه. اگر تعداد کاراکترها بیشتر شد ... قرار بگیره و داخل تگ 
title
مقدار کلی نشون داده بشه

2021-08-07 05:43 UTC, rsangin commented on styles/scss/main.scss
> +    color: $content-color;
در تم لایت این قسمت contrast
مناسبی ندارد

2021-08-07 05:43 UTC, rsangin commented on login.html
>          <section>
بهتره داخل تگ فرم قرار بگیره و عرض کمتری داشته باشه

2021-08-07 05:43 UTC, rsangin commented on styles/scss/main.scss
> +  color: $content-color;
بهتره این قسمت هم مثل هاور شود تا مشخص تر باشد

2021-08-07 10:24 UTC, spneshaei commented on scripts/register.js
> +    let response = await fetch('http://130.185.120.192:5000/user/register', {
با سلام؛ اعمال شد.

2021-08-07 10:27 UTC, spneshaei commented on scripts/register.js
> +async function register() {
با سلام؛ اعمال شد.

2021-08-07 10:29 UTC, spneshaei commented on scripts/music.js
> +        twoXButton.style.color = "#4C956C";
با سلام؛ اعمال شد.

2021-08-07 10:30 UTC, spneshaei commented on scripts/login.js
> +            confirmButtonText: 'بازگشت',
با سلام؛ اعمال شد.

2021-08-07 10:32 UTC, spneshaei commented on scripts/music-list.js
> +// let musics = [
با سلام؛ اعمال شد.

2021-08-07 10:44 UTC, spneshaei commented on styles/scss/main.scss
> +  color: $content-color;
با سلام؛ اصلاح شد.

2021-08-08 04:21 UTC, spneshaei commented
با سلام

تمامی کامنت‌های صفحه به همراه سایر کامنت‌های از پیش نوشته شده، اعمال شدند؛ در صورت صدور اجازه، merge را انجام خواهد داد.

2021-08-08 09:05 UTC, rsangin commented on styles/scss/main.scss
> +  color: $content-color;
به نظر هنوز مثل قبله

2021-08-08 19:06 UTC, MRSadeghi78 requested changes
پوشه های
node_modules و .idea
رو بذارین داخل گیت ایگنور

2021-08-08 19:22 UTC, spneshaei commented
> پوشه های
> node_modules و .idea
> رو بذارین داخل گیت ایگنور

با سلام؛ اصلاح شد.

@rsangin اگر از طرف شما هم مورد دیگری نیست، مرج رو انجام بدیم.

2021-08-09 05:14 UTC, rsangin approved these changes

2021-08-09 08:47 UTC, AshkanShakiba approved these changes

2021-08-09 10:42 UTC, MRSadeghi78 approved these changes

2021-08-09 12:52 UTC, merged